app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from app.models import User, Organisation, Role



class UserRegisterForm(FlaskForm):
    
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    firstname = StringField('First Name')
    lastname = StringField('First Name')
    is_admin = BooleanField('Is Admin')
    active = BooleanField('Active')
    password = PasswordField('Password', [DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired() , EqualTo('password')])
    submit=SubmitField('Register')


    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')


class UserAssignForm(FlaskForm):
    """
    Form for admin to assign organisation and roles to employees
    """
   
    organisation = QuerySelectField(query_factory=lambda: Organisation.query.all(),
                                  get_label="name")
    role = QuerySelectField(query_factory=lambda: Role.query.all(),
                            get_label="name")
    
    submit = SubmitField('Submit')


class OrganisationForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    code = StringField('Organisation Code', validators=[DataRequired()])
    vrn = StringField('Vat Registration Number', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Submit')


class RoleForm(FlaskForm):
    """
    Form for admin to add or edit a role
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    
    
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

app/home/__init__.py
from flask import Blueprint

bp = Blueprint('home', __name__)

from app.home import routes

app/home/routes.py
from flask import  abort, flash, render_template, redirect, request, url_for, g, \
    jsonify, current_app
from werkzeug.urls import url_parse
from flask_login import login_required, current_user
from app import db

from app.auth.forms import LoginForm
from app.home.forms import OrganisationForm, UserRegisterForm, UserAssignForm, RoleForm
from app.home import bp
from app.models import User, Organisation, Role, user_roles



def check_admin():
    """
    Prevent non-admins from accessing the page
    """
    if not current_user.has_admin():
        abort(403)



@bp.route('/index', methods=['GET','POST'])

def index():
    form = LoginForm()
    
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        return redirect(url_for('auth.login')) 

    return render_template('home/landing.html', form=form)



@bp.route('/dashboard', methods=['GET','POST'])
@login_required
def dashboard():
    """
    Prevent non-admins from accessing the page
    """
    
    return render_template('home/dashboard.html', title="Dashboard")

# organisation Views


@bp.route('/register', methods=['GET', 'POST'])
@login_required
def register_user():

    check_admin()

    form = UserRegisterForm()

    if request.method=="POST" and form.validate_on_submit():
        user = User(username=form.username.data, 
                    email=form.email.data, 
                    first_name=form.firstname.data,
                    last_name=form.lastname.data,
                    is_admin=form.is_admin.data,
                    active=form.active.data  
                    )
        
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User registered successfully')
        return redirect(url_for('home.list_users'))
    return render_template('home/register_user.html', title='Register User', form=form)


@bp.route('/users')
@login_required
def list_users():
    """
    List all employees
    """
    check_admin()
    
    form = UserRegisterForm()
    users = User.query.all()
    return render_template('home/users.html', form=form,
                           users=users, title='Users')


@bp.route('/users/assign/<int:id>', methods=['GET', 'POST'])
@login_required
def assign_user(id):
    """
    Assign a department and a role to an employee
    """
    check_admin()

    user = User.query.get_or_404(id)
    

    # prevent admin from being assigned a organisation or role
    if user.has_admin():
        abort(403)

    form = UserAssignForm(obj=user)
    if request.method=="POST" and form.validate_on_submit():
        user.organisation = form.organisation.data
        
        user.roles.append(form.role.data)
        db.session.add(user)
        db.session.commit()
        flash('You have successfully assigned a organisation and role.')

        # redirect to the roles page
        return redirect(url_for('home.list_users'))

    return render_template('home/user.html', id=id,
                           user=user, form=form,
                           title='Assign User')



@bp.route('/users/delete/<int:id>', methods=['GET','POST'])
@login_required
def delete_user(id):

    '''
    Delete a user from the database
    '''
    check_admin()

    user = User.query.get_or_404(id)
    user.delete()

    flash('You have successfully deleted the user.')

    # redirect to the users page
    return redirect(url_for('home.list_users'))

    return render_template('home/dashboard.html')



@bp.route('/organisations', methods=['GET', 'POST'])
@login_required
def organisations():
    """
    List all organisations
    """
    check_admin()

    form=OrganisationForm()
    organisations = Organisation.query.all()

    return render_template('home/organisations.html', form=form,
                           organisations=organisations, title="Organisations")


@bp.route('/organisations/add', methods=['GET', 'POST'])
@login_required
def add_organisation():
    """
    Add a organisation to the database
    """
    check_admin()

    add_organisation = True

    form = OrganisationForm()
    if request.method=="POST" and form.validate_on_submit():
        organisation = Organisation(code=form.code.data, vrn=form.vrn.data,
                                    name=form.name.data)
        try:
            # add organisation to the database
            db.session.add(organisation)
            db.session.commit()
            flash('You have successfully added a new organisation.')
        except:
            # in case organisation name already exists
            flash('Error: organisation name already exists.')

        # redirect to organisations page
        return redirect(url_for('home.organisations'))

    # load organisation template
    return render_template('home/organisation.html', action="Add", id=None,
                           add_organisation=add_organisation, form=form,
                           title="Add Organisation")


@bp.route('/organisation/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_organisation(id):
    """
    Edit a organisation
    """
    check_admin()

    add_organisation = False

    organisation = Organisation.query.get_or_404(id)
    form = OrganisationForm(obj=organisation)
    if request.method == "POST" and form.validate_on_submit():
        organisation.code = form.code.data
        organisation.vrn = form.vrn.data
        organisation.name = form.name.data
        db.session.commit()
        flash('You have successfully edited the organisation.')

        # redirect to the organisations page
        return redirect(url_for('home.organisations'))

    form.code.data = organisation.code
    form.vrn.data = organisation.vrn
    form.name.data = organisation.name
    return render_template('home/organisation.html', id=id , action="Edit",
                           add_organisation=add_organisation, form=form,
                           organisation=organisation, title="Edit Organisation")


@bp.route('/organisation/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_organisation(id):
    """
    Delete a organisation from the database
    """
    check_admin()

    organisation = Organisation.query.get_or_404(id)
    db.session.delete(organisation)
    db.session.commit()
    flash('You have successfully deleted the organisation.')

    # redirect to the organisations page
    return redirect(url_for('home.organisations'))

    return render_template(title="Delete Organisation")



# Role Views


@bp.route('/roles')
@login_required
def list_roles():
    check_admin()
    """
    List all roles
    """

    form=RoleForm()
    roles = Role.query.all()
    return render_template('home/roles.html', form=form,
                           roles=roles, title='Roles')


@bp.route('/roles/add', methods=['GET', 'POST'])
@login_required
def add_role():
    """
    Add a role to the database
    """
    check_admin()

    add_role = True

    form = RoleForm()
    if form.validate_on_submit():
        role = Role(name=form.name.data,
                    description=form.description.data)

        try:
            # add role to the database
            db.session.add(role)
            db.session.commit()
            flash('You have successfully added a new role.')
        except:
            # in case role name already exists
            flash('Error: role name already exists.')

        # redirect to the roles page
        return redirect(url_for('home.list_roles'))

    # load role template
    return render_template('home/role.html', add_role=add_role,
                           form=form, title='Add Role')


@bp.route('/roles/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_role(id):
    """
    Edit a role
    """
    check_admin()

    add_role = False

    role = Role.query.get_or_404(id)
    form = RoleForm(obj=role)
    if request.method=="POST" and form.validate_on_submit():
        role.name = form.name.data
        role.description = form.description.data
        db.session.add(role)
        db.session.commit()
        flash('You have successfully edited the role.')

        # redirect to the roles page
        return redirect(url_for('home.list_roles'))

    form.description.data = role.description
    form.name.data = role.name
    return render_template('home/role.html', id=id,  add_role=add_role,
                           form=form, title="Edit Role")


@bp.route('/roles/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_role(id):
    """
    Delete a role from the database
    """
    check_admin()

    role = Role.query.get_or_404(id)
    db.session.delete(role)
    db.session.commit()
    flash('You have successfully deleted the role.')

    # redirect to the roles page
    return redirect(url_for('home.list_roles'))

    return render_template(title="Delete Role")

app/templates/home/dashboard.html
{% extends "layouts/main_base.html" %}

{% block title %}title{% endblock %}

{% block sidenav %}  
	  
{% endblock %}

{% block header %}
<div class="row">

    {% if current_user.is_admin %}
    
        <div class="box red pull-left">{{session['orgname']}}
        </div>
        <div class="info-box"><h1> Admin Dashboard</h1></div>
    
    {% else %}
        <div class="box green pull-left">{{session['orgname']}} 
        </div>
        <div class="info-box"><h1> User Dashboard</h1></div>
        
    {% endif %}
    

</div>        <!-- /.info-box-content -->
{% endblock %}

{% block content %}
    
          <!-- /.info-box -->
    <h3>For administrators only!</h3>
    <hr class="intro-divider">
              
    <div class="container">
     	
        

    </div>    



   
{% endblock %}

app/templates/home/organisation.html
{% extends "layouts/main_base.html" %}



{% block title %}
    title
{% endblock %}
{% block content %}
<h1>Admin Dashboard</h1>
    <h3>For administrators only!</h3>
    <hr class="intro-divider">

<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_organisation %}
                <h1>Add Organisation</h1>
            {% else %}
                <h1>Edit Organisation</h1>
            {% endif %}
            <br/>
            
        </div>
        <div class="row">
          <div class="col-md-10">


        {% if add_organisation %}
            <form action="{{ url_for('home.add_organisation') }}" class="form" method="post" >
        {% else %}
            <form action="{{ url_for('home.edit_organisation', id=id) }}" class="form" method="post" >
        {% endif %}
              {{ form.hidden_tag() }}
              <table class="table table-bordered" id="editableTable">
                  <thead class="table-blue">
                    <tr>
                      <th>Org Code</th>
                      <th>Vat Reg. No.</th>
                      <th>Org Name</th>
                    </tr>
                  </thead>
                  <tr>
                    <td>
                      <div class="form-group">
                        <div>
                          {{ form.code(class="form-control", horizontal_columns=('lg', 6, 3)) }} 
                        </div>
                      </div>
                    </td>
                    <td>
                      <div class="form-group">
                        <div>
                          {{ form.vrn(class="form-control", horizontal_columns=('lg', 6, 3)) }} 
                        </div>
                      </div>

                    </td>
                    <td>  
                      <div class="form-group">
                        <div>
                          {{ form.name(class="form-control", horizontal_columns=('lg', 6, 3)) }} 
                        </div>
                      </div>
                    </td>
                  </tr>
              </table>
            <button type="submit" class="btn btn-info pull-right edit-row" >Save Changes</button>
          </form>
          </div>
        </div>
          
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/organisations.html
{% extends "layouts/main_base.html" %}

{% block title %}title{% endblock %}

{% block sidenav %}  
	  
{% endblock %}

{% block header %}Test{% endblock %}

{% block content %}
    <h1>Admin Dashboard</h1>
    <h3>For administrators only!</h3>

    
    <hr class="intro-divider">
    
    <div class="container">
    	<div class="row">
    		<div class="col-md-10">
      			<br>
      			<a href="{{ url_for('home.add_organisation') }}" class="btn btn-info pull-right add-row">
              <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp; Add Organisation</a>
            </a>
    		</div>
  		</div>
      <p></p>
      {% if organisations %}
  		<div class="row">
    		<div class="col-md-10">
    			<form action="" method="post" name="OrganisationForm">
    				{{ form.hidden_tag() }}
    			<table class="table table-bordered" id="editableTable">
			        <thead class="table-blue">
			          <tr>
			            <th>Code</th>
			            <th>Vat Reg. No.</th>
			            <th>Name</th>
			            <th>Edit</th>
			          </tr>
			        </thead>
			        <tbody>
			        	{% for org in organisations %}
			        		<tr data-id="{{ org.id }}">
			        			<td data-field="code">{{ org.code }}</td>
			        			<td data-field="vrn">{{ org.vrn }}</td>
			        			<td data-field="name">{{ org.name }}</td>
			        			<td>
			        				<a href="{{ url_for('home.edit_organisation', id=org.id) }}"  class="btn btn-sm btn-default edit" title="Edit" >
                						<span class="glyphicon glyphicon-edit"></span>
              				</a>
               				<a href="{{ url_for('home.delete_organisation', id=org.id) }}" class="btn btn-sm btn-default" title="Delete">
                						<span class="glyphicon glyphicon-trash"></span>
              				</a>
			        			</td>
			        		</tr>

			        	{% endfor %}
			        </tbody>

            </table>
          </form>
    		</div>
    	</div>
      {% else %}
        <div style="text-align: center">
        <h3> No organisations have been added. </h3>

      {% endif %}
    </div>       
    
<!--- Modal --->    

        
{% endblock %}

{% block script %}{% endblock %}

app/templates/home/register_user.html
{% extends "layouts/main_base.html" %}

{% block title %}title{% endblock %}

{% block sidenav %}  
	  
{% endblock %}

{% block header %}
    <h1>Admin Dashboard</h1>
    <h3>For administrators only!</h3>
{% endblock %}

{% block content %}
    
    
    <div class="row">
        <div class="centred">
            <div class="signup-form">
                <form action="{{ url_for('home.register_user') }}" method="post">
                    {{ form.hidden_tag() }}
                    <h2>Register</h2>
                    <p class="hint-text">Create user account</p>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-6">
                                {{ form.firstname(class="form-control", placeholder="First Name") }}
                            </div>
                            <div class="col-xs-6">
                                {{ form.lastname(class="form-control", placeholder="Last Name") }}
                            </div>
                        </div>          
                    </div>
                    <div class="form-group">
                        {{ form.username(class="form-control", placeholder="Username") }}
                    </div>
                    <div class="form-group">
                        {{ form.email(class="form-control", placeholder="Email Address") }}
                    </div>
                    <div class="form-group">
                        {{ form.password(class="form-control", placeholder="Password") }}
                    </div>
                    <div class="form-group">
                        {{ form.password2(class="form-control", placeholder="Confirm Password") }}
                    </div>        
                    <div class="form-group">
                        <label class="checkbox-inline"><input type="checkbox" name="active"> Active User </label>
                    </div>
                    <div class="form-group">
                        <label class="checkbox-inline"><input type="checkbox" name="is_admin"> Admin User </label>
                        
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-lg btn-block">Register</button> 
                    </div>
                </form>
            </div>
        </div>
    </div>             
{% endblock %}

app/templates/home/role.html
{% extends "layouts/main_base.html" %}



{% block title %}
    title
{% endblock %}
{% block content %}
<h1>Admin Dashboard</h1>
    <h3>For administrators only!</h3>
    <hr class="intro-divider">

<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_role %}
                <h1>Add Role</h1>
            {% else %}
                <h1>Edit Role</h1>
            {% endif %}
            <br/>
            
        </div>
        <div class="row">
          <div class="col-md-10">


        {% if add_role %}
            <form action="{{ url_for('home.add_role') }}" class="form" method="post" >
        {% else %}
            <form action="{{ url_for('home.edit_role', id=id) }}" class="form" method="post" >
        {% endif %}
              {{ form.hidden_tag() }}
              <table class="table table-bordered" id="editableTable">
                  <thead class="table-blue">
                    <tr>
                      <th width="30%">Name</th>
                      <th width="70%">Description</th>
                      
                    </tr>
                  </thead>
                  <tr>
                    <td>
                      <div class="form-group">
                        <div>
                          {{ form.name(class="form-control", horizontal_columns=('lg', 6, 3)) }} 
                        </div>
                      </div>
                    </td>
                    <td>
                      <div class="form-group">
                        <div>
                          {{ form.description(class="form-control", horizontal_columns=('lg', 6, 3)) }} 
                        </div>
                      </div>

                    </td>
                    
                  </tr>
              </table>
            <button type="submit" class="btn btn-info pull-right edit-row" >Save Changes</button>
          </form>
          </div>
        </div>
          
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/roles.html
{% extends "layouts/main_base.html" %}

{% block title %}title{% endblock %}

{% block sidenav %}  
	  
{% endblock %}

{% block header %}Test{% endblock %}

{% block content %}
	<h1>Admin Dashboard</h1>
	<h3>For administrators only!</h3>

	<hr class="intro-divider">
    
    <div class="container">
    	<div class="row">
    		<div class="col-md-10">
      			<br>
      			<a href="{{ url_for('home.add_role') }}" class="btn btn-info pull-right add-row">
              <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp; Add Role</a>
            </a>
    		</div>
  		</div>
        <p></p>
        {% if roles %}
  		<div class="row">
    		<div class="col-md-10">
    			<form action="" method="post" name="OrganisationForm">
    				{{ form.hidden_tag() }}
    			<table class="table table-bordered" id="editableTable">
			        <thead class="table-blue">
			          <tr>
			            <th width="25%">Name</th>
			            <th width="35%">Description</th>
			            <th width="15%">User count</th>
			            <th width="25%">Edit</th>
			          </tr>
			        </thead>
			        <tbody>
			        	{% for role in roles %}
			        		<tr data-id="{{ role.id }}">
			        			<td data-field="name">{{ role.name }}</td>
			        			<td data-field="description">{{ role.description }}</td>
			        			<td>{% if role.users %}
                      			{{ role.users.count('*') }}
                    		{% else %}
                    				0
                    		{% endif %}
                    </td>
			        			<td>
			        				<a href="{{ url_for('home.edit_role', id=role.id) }}"  class="btn btn-sm btn-default edit" title="Edit" >
                						<span class="glyphicon glyphicon-edit"></span>
              						</a>
               						<a href="{{ url_for('home.delete_role', id=role.id) }}" class="btn btn-sm btn-default" title="Delete">
                						<span class="glyphicon glyphicon-trash"></span>
              						</a>
			        			</td>
			        		</tr>

			        	{% endfor %}
			        </tbody>

            </table>
          </form>
    		</div>
    	</div>
    	{% else %}
    		<div style="text-align: center">
    		<h3> No roles have been added. </h3>

    	{% endif %}
    </div>       
    
   
<!--- Modal --->    

        
{% endblock %}

{% block script %}{% endblock %}

app/templates/home/user.html
{% extends "layouts/main_base.html" %}



{% block title %}
    title
{% endblock %}
{% block content %}
<h1>Admin Dashboard</h1>
    <h3>For administrators only!</h3>
    <hr class="intro-divider">

<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            <h1>Edit User</h1>
            
            <br/>
            
        </div>
        <div class="row">
          <div class="col-md-10">


        
            <form action="{{ url_for('home.assign_user', id=id) }}" class="form" method="post" >
        
              {{ form.hidden_tag() }}
              <table class="table table-bordered" id="editableTable">
                  <thead class="table-blue">
                    <tr>
                      <th width="50%">Organisation</th>
                      <th width="50%">Role</th>
                      
                    </tr>
                  </thead>
                  <tr>
                    <td>
                      <div class="form-group">
                        <div>
                          {{ form.organisation(class="form-control", horizontal_columns=('lg', 6, 3)) }} 
                        </div>
                      </div>
                    </td>
                    <td>
                      <div class="form-group">
                        <div>
                          {{ form.role(class="form-control", horizontal_columns=('lg', 6, 3)) }} 
                        </div>
                      </div>

                    </td>
                    
                  </tr>
              </table>
            <button type="submit" class="btn btn-info pull-right edit-row" >Save Changes</button>
          </form>
          </div>
        </div>
          
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/users.html
{% extends "layouts/main_base.html" %}

{% block title %}title{% endblock %}

{% block sidenav %}  
	  
{% endblock %}

{% block header %}
	<h1>Admin Dashboard</h1>
	<h3>For administrators only!</h3>
{% endblock %}

{% block content %}
	
    
    <div class="container">
    	<div class="row">
    		<div class="col-md-10">
      			<br>
      			<a href="{{ url_for('home.register_user') }}" class="btn btn-info pull-right add-row">
              <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp; Add User</a>
            </a>
    		</div>
  		</div>
        <p></p>
        {% if users %}
  		<div class="row">
    		<div class="col-md-10">
    			<form action="" method="post" name="OrganisationForm">
    				
    			<table class="table table-bordered" id="editableTable">
			        <thead class="table-blue">
			          <tr>
			            <th width="15%">Username</th>
			            <th width="20%">Name</th>
			            <th width="15%">Email</th>
						<th width="10%">Organisation</th>
						<th width="15%">Role</th>
						<th width="10%">Active</th>
			            <th width="15%">Edit</th>
			          </tr>
			        </thead>
			        <tbody>
			        	{% for user in users %}
			        		{% if user.is_admin %}
		                    <tr style="background-color: #aec251; color: white;">
		                        <td> <i class="fa fa-key"></i>{{ user.username }} </td>
		                        <td> N/A </td>
		                        <td> N/A </td>
		                        <td> N/A </td>
		                        <td> N/A </td>
		                        <td> N/A </td>
		                        <td> N/A </td>
		                    </tr>
                			{% else %}
			        		<tr data-id="{{ user.id }}">
			        			<td data-field="name">{{ user.username }}</td>
			        			<td data-field="description">{{ user.first_name }} {{ user.last_name }}</td>
			        			<td data-field="email">{{ user.email }}</td>
			        			<td data-field="organisation">{% if user.organisation %}
                          										{{ user.organisation.name }}
                        									  {% else %}
                         										 -
                        									  {% endif %}</td>
 								<td data-field="role">{% if user.roles %}
                          								{{ user.roles }}
                        							  {% else %}
                         								 -
                        							  {% endif %}</td>
 								<td data-field="active">{{ user.active }}</td>
			        			<td>
			        				<a href="{{ url_for('home.assign_user', id=user.id) }}"  class="btn btn-sm btn-default edit" title="Edit" >
                						<span class="glyphicon glyphicon-edit"></span>
              						</a>
               						<a href="{{ url_for('home.delete_user', id=user.id) }}" class="btn btn-sm btn-default" title="Delete">
                						<span class="glyphicon glyphicon-trash"></span>
              						</a>
			        			</td>
			        		</tr>
			        		{% endif %}
			        	{% endfor %}
			        </tbody>

            </table>
          </form>
    		</div>
    	</div>
    	{% endif %}
    </div>       
    
    

    
<!--- Modal --->    

        
{% endblock %}

{% block script %}{% endblock %}